### ISSUE TITLE
Links from the blog still go to http://vsoch.github.io/nipy-jekyll

### ISSUE THREAD

**Issue by arokem** [nipy/nipy.github.com#13]
For example, if you click: blog => home

**Comment by vsoch** [comment]
Oh yes, that needs to be fixed on tumblr. Will do right now.

**Comment by vsoch** [comment]
Take a look now. All should be fixed! If it suits you, you can close this issue.

**Comment by arokem** [comment]
I think that you want to redirect it to nipy.org, rather than
nipy.org/home.html

In one case, the explanatory text at the top of the page does appear, and
in the other it does not.

Ariel

**Comment by vsoch** [comment]
Give a try now.

**Comment by vsoch** [comment]
I think this is fixed, closing the issue,

**Comment by arokem** [comment]
yup yup
