### ISSUE TITLE
Fix circle artifact previewing

### ISSUE THREAD

**Issue by vsoch** [nipy/nipy.github.com#17]
Just an issue with the regular expression (sed) command

**Comment by bcipolli** [comment]
@vsoch From the mailing list, took at the current circle build. Looks like things are working well; I don't see any URL strangeness.

The current issue is: the HTML files refers to `css/main.css`; all I see there is `css/main.scss`. Not sure how that's supposed to be compiled into `css/main.css`.

That's the problem I see; the URLs look beautiful.

**Comment by bcipolli** [comment]
...and then I just went back to the site, and none of the `css` files can be found anymore, even the static ones (e.g. `css/bootstrap.min.css`). So strange.

**Comment by bcipolli** [comment]
I see. The issue is that the build # for the include files is off by one in the URLs.. Will take a look

**Comment by vsoch** [comment]
Fixed! Excellent. I was using the PREVIOUS variable before, I'm not sure the generic BUILD NUM was available months ago (I think previous referred to the one that just happened, but I'm not sure now). Thanks so much for fixing! I'm going to close this issue.
