### ISSUE TITLE
Update DNS to support HTTPS on nipy.org

### ISSUE THREAD

**Issue by effigies** [nipy/nipy.github.com#49]
GitHub [now supports HTTPS for custom domains](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/). We are using `A` records, rather than `CNAME` or `ALIAS`, so we either need to switch to these other record types or update the IP addresses in the `A` records.

I'm not sure who administers the DNS records for nipy.org, but it would be nice to support HTTPS, if possible.

See also: [Setting up an apex domain](https://help.github.com/articles/setting-up-an-apex-domain/)

**Comment by matthew-brett** [comment]
@jarrodmillman - would you mind doing the honors?

**Comment by effigies** [comment]
Hi @jarrodmillman, is this something you're able to do, or I could help with?

**Comment by vsoch** [comment]
This is probably linked in the blog above, but in case not [here is how to do it!](https://help.github.com/articles/troubleshooting-custom-domains/#https-errors)

**Comment by effigies** [comment]
Just a bump on this. @jarrodmillman Anything I can do to help make this happen?

**Comment by jarrodmillman** [comment]
@effigies Thanks for ping me again, I missed the ones this summer (sorry about that).

The `A` record was changed from
```
$ dig +noall +answer nipy.org
nipy.org.               12189   IN      A       192.30.252.154
nipy.org.               12189   IN      A       192.30.252.153
```
to
```
$ dig +noall +answer nipy.org
nipy.org.               14400   IN      A       185.199.109.153
nipy.org.               14400   IN      A       185.199.108.153
nipy.org.               14400   IN      A       185.199.110.153
nipy.org.               14400   IN      A       185.199.111.153
```

Please let me know if you need me to do anything else.

**Comment by effigies** [comment]
Cool, that works. I set nipy.org and nipy.org/nibabel to enforce HTTPS, and the experience seems identical.
