### ISSUE TITLE
[greater good pledge] request for participation

### ISSUE THREAD

**Issue by vsoch** [nipy/nipy.github.com#54]
hey nipy family!

I'm creating a new initiative, [The Greater Good](https://good-labs.github.io/greater-good-pledge/) that aims to highlight projects with no underlying incentives or ulterior motives - those that are "for the greater good." The nipy family of tools (I believe) fit strongly within the criteria, and I'm hoping that the community would like to participate. Participation simply means adding the community name to the pledge, and then (optionally) adding a badge to any associated project repos.

Details are provided at the page, and any maintainers / users here are welcome to also join the organization [The Good Labs](https://www.github.com/good-labs) if open source transparency is important to them. It's still early (I'm going to be creating media and other community interactions) and right now I'm getting in touch with projects that I've worked with.

**Comment by vsoch** [comment]
Just added some [FAQ](https://good-labs.github.io/greater-good-pledge/faq/) and please see active discussion here https://github.com/pydicom/pydicom/issues/842#issuecomment-488366124 about making it more about disclosure (less about profits). Feel free to jump in!

**Comment by arokem** [comment]
Hello @vsoch! I am +1 for NIPY signing this pledge. Looks like we are squarely within the definition.

**Comment by vsoch** [comment]
Awesome!  I’d suggest waiting until there is an official release out so that you can link with a particular version that you’ve signed.  I can ping here again when that’s done :-)

**Comment by effigies** [comment]
I'm also +1, fwiw.

**Comment by satra** [comment]
+1 - sorry this fell of the radar.

**Comment by vsoch** [comment]
Awesome! I'll open a PR with the badge.

**Comment by vsoch** [comment]
See https://github.com/nipy/nipy.github.com/pull/62. The badge added is:

[![https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg](https://good-labs.github.io/greater-good-affirmation/assets/images/badge.svg)](https://good-labs.github.io/greater-good-affirmation)
