### ISSUE TITLE
Change `tumblr` links for links to `neurostars`

### ISSUE THREAD

**Issue by jhlegarreta** [nipy/nipy.github.com#68]
I've noticed that there there are a few links to `tumblr` throughout the website (e.g. [contribute](https://nipy.org/contribute.html); `neurostars` is mentioned in the [help](https://nipy.org/help.html) and in the Discourse instance as the place to ask questions, though.

I've also noticed that the last question on `tumblr` was 2 years ago.

Maybe `tumblr` can be kept for blog posts, but maybe `tumblr` as a place to get help should be changed to `neurostarts` and/or the neuroimaging mailing list? And maybe the latter two could be better distinguished in their purpose when changing this?

**Comment by jhlegarreta** [comment]
On a slightly related note, the Discourse post https://nipy.discourse.group/t/welcome-to-the-nipy-discourse-instance/7 could be made a banner in the Discourse instance, so that it is always visible. And a link to the Nipy website could also be beneficial.

**Comment by arokem** [comment]
Yes: that would probably be for the best. That tumblr site was not much of
a hit.

**Comment by jhlegarreta** [comment]
Thanks @arokem . I can propose the change if there is enough agreement for it.
