### ISSUE TITLE
Discourse?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [nipy/nipy.github.com#73]
Pages https://nipy.org/contribute.html and https://github.com/nipreps contain a link to [**nipy.discourse.group**](https://nipy.discourse.group/).

This doesn't look like a valid DNS name.

![nipy discourse group](https://github.com/nipy/nipy.github.com/assets/3234522/79829769-f996-4fc1-bfb2-c615af01000f)

**Comment by DimitriPapadopoulos** [comment]
Should I use the [nipy](https://neurostars.org/tag/nipy) tag on [NeuroStars](https://neurostars.org/) instead?

**Comment by effigies** [comment]
It got killed for inactivity. Matthew migrated the threads to https://github.com/orgs/nipy/discussions

**Comment by DimitriPapadopoulos** [comment]
Ah thank you. Should I submit a PR to fix that?

**Comment by effigies** [comment]
Please do!
